#define MICROPY_HW_BOARD_NAME "WLR089U0"
#define MICROPY_HW_MCU_NAME   "SAML21/SAMR34J18B"
#define WLR089U0  (1)
#define MICROPY_HW_DFLL_USB_SYNC    (1)
#define MICROPY_HW_XOSC32K          (1)
#define MICROPY_HW_MCU_OSC32KULP    (0)
#define MICROPY_HW_SPIFLASH (1)
#define MICROPY_HW_SPIFLASH_ID (5)
#define MICROPY_HW_SPIFLASH_SIZE_BITS (16 * 1024 * 1024)
